spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: rule-service
          uri: lb://RULE-SERVICE
          predicates:
            - Path=/rule/**
          filters:
            - name: CircuitBreaker
              args:
                name: rule-service
                fallbackuri: forward:/ruleFallback
        - id: rms-service
          uri: lb://RMS-SERVICE
          predicates:
            - Path=/rms/**
          filters:
            - name: CircuitBreaker
              args:
                name: rms-service
                fallbackuri: forward:/rmsFallBack
        - id: adaptor-service
          uri: lb://ADAPTOR-SERVICE
          predicates:
            - Path=/adaptor/**
          filters:
            - name: CircuitBreaker
              args:
                name: adaptor-service
                fallbackuri: forward:/adaptorFallback
server:
  port: 8050

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
